services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-key
      - key: DISCORD_TOKEN
        value: your-discord-token
